using MCQDAOnAbp.QuestionBankService.EntityFrameworkCore;
using Xunit;

namespace MCQDAOnAbp.QuestionBankService.EntityFrameworkCore;

public class QuestionBankServiceEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<QuestionBankServiceEntityFrameworkCoreFixture>
{

}
