using Xunit;

namespace MCQDAOnAbp.TrainingProgramService.EntityFrameworkCore;

[CollectionDefinition(TrainingProgramServiceTestConsts.CollectionDefinitionName)]
public class TrainingProgramServiceEntityFrameworkCoreCollection : ICollectionFixture<TrainingProgramServiceEntityFrameworkCoreFixture>
{

}
