using MCQDAOnAbp.TrainingProgramService.EntityFrameworkCore;
using Xunit;

namespace MCQDAOnAbp.TrainingProgramService.EntityFrameworkCore;

public class TrainingProgramServiceEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<TrainingProgramServiceEntityFrameworkCoreFixture>
{

}
